id = "routeros"
name = "RouterOS Script"
version = "0.5.0"
schema_version = 1
authors = ["Damir Manyapov <2977374@gmail.com>"]
description = "MikroTik RouterOS .rsc support: syntax highlighting and offline completion"
repository = "https://github.com/DamirManyapov/zed-routeros"

[language_servers.routeros-lsp]
name = "RouterOS LSP"
languages = ["RouterOS Script"]

[grammars.routeros]
repository = "https://github.com/DamirManyapov/tree-sitter-routeros"
rev = "f1d156aee9b75900d41cde193d964c2b3bd373a4"
